---
# handlers file for db_role
- name: restart nginx service
  service:
      name: nginx
      state: restarted
- name: restart php-fpm service
  service:
      name: php8.3-fpm
      state: restarted
- name: restart mysql service
  service:
      name: mariadb
      state: restarted
