- name: myplay1
  hosts: all
  become: true
  tasks:
    - name: Update APT Cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: inventory_hostname in groups['webserver']
    - name: Start Nginx service
      service:
        name: nginx
        state: started
      when: inventory_hostname in groups['webserver']
    - name: Install PHP
      apt:
        name: php
        state: present
      when: inventory_hostname in groups['appserver']
    - name: Install PHP 8.3-FPM
      apt:
        name: php8.3-fpm
        state: present
      when: inventory_hostname in groups['appserver']
    - name: Start PHP-FPM service
      service:
        name: php8.3-fpm
        state: started
      notify: restart php-fpm service
      when: inventory_hostname in groups['appserver']
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present
      when: inventory_hostname in groups['dbserver']
    - name: Start MySQL (MariaDB) service
      service:
        name: mariadb
        state: started
      notify: restart mysql service
      when: inventory_hostname in groups['dbserver']
