- name: myplay1
  hosts: localhost
  become: true
  connection: local
  tasks:
   - name: install LEMP
     apt:
      name: "{{ item }}"
      state: present
     with_items:
      - nginx
      - php
      - php8.3-fpm
      - mysql-server
   - name: start all service
     service:
      name: "{{ item }}"
      state: started
     with_items:
      - nginx
      - php8.3-fpm
      - mysql
   - name: restart all service
     service:
      name: "{{ item }}"
      state: restarted
     with_items:
      - nginx
      - php8.3-fpm
      - mysql
