- name: install mysql
  apt:
    name: mariadb-server
    state: present
- name: start mysql
  service:
    name: mariadb
    state: started
  notify: restart nginx service
  notify: restart php-fpm service
  notify: restart mysql service
